# Generated by Django 2.2.6 on 2019-10-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='bodyText',
            field=models.TextField(null=True),
        ),
    ]
