# Generated by Django 2.2.6 on 2019-10-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenseDate', models.DateTimeField()),
                ('expenseCount', models.IntegerField()),
                ('target', models.CharField(max_length=50)),
                ('forProductionOrConsume', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomeDate', models.DateTimeField()),
                ('incomeCount', models.IntegerField()),
                ('origin', models.CharField(max_length=50)),
            ],
        ),
    ]
