# Generated by Django 2.2.6 on 2019-10-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='forProductionOrConsume',
            field=models.CharField(choices=[('p', 'Production'), ('c', 'Consume')], max_length=20),
        ),
    ]
