# Generated by Django 2.2.6 on 2019-10-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=20)),
                ('field', models.CharField(choices=[('cs', 'Computer Science'), ('phil', 'philosophy'), ('eco', 'economy'), ('pol', 'politics')], max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('progress', models.CharField(choices=[('0', '0%'), ('1', '0%~25%'), ('2', '25%~50%'), ('3', '50%~75%'), ('4', '75%~100%')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=30)),
                ('DateField', models.DateField()),
                ('description', models.TextField()),
                ('review', models.TextField()),
            ],
        ),
    ]
